### ISSUE TITLE
Reduce CPU Cycles

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1039]
**Is your feature request related to a problem? Please describe.**
- Recent changes in 3.6.2 branch (already merged with Master) have increased the CPU utilizations and inadvertently caused negative sleep time.
- VisualVM highlights the methods that use a lot of CPU cycles.

**Describe the solution you desire to see**
- According to VisualVM, on Thread-0, the top 3 consumers of cpu resources are : 
1. 51.5 % - `Settlement::timePssingCitizens`
2. 23.9% - `Settlement::timePassing`
3. 15.8% - `BuildingManager::timePassing`
![image](https://github.com/mars-sim/mars-sim/assets/1168584/1b160a9f-12aa-4836-8706-3230773eab9a)

If going inside `Settlement::timePssingCitizens`, two tasks are highlighted : 
1. 8.5% - `TendGreenhoue::tendingPhase()`
2. 11% - `DigLocal::performMappedPhase()`

![image](https://github.com/mars-sim/mars-sim/assets/1168584/8e7de437-7ddf-4d13-9aed-16ae7f6a7462)

However, in another snapshot, a majority 44% in spent in `Mind::timePassing()` -> `WalkRoverInterrior::walkingPhase` -> `EquipmentInventory.getModifiedMass`.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/0d2425b9-a5cc-4381-a3d4-dd1b4e762ba9)

**Comment by bevans2000** [comment]
But these methods have not changed since 3.6.0 so surely they cannot be the reason for it going slower since then?
What about the excessive sleep messages seen? That suggests there was a lot of wasted logic going on and the pending tasks that failed to start.
The slowdown is not immediately but occurs once people start eva

**Comment by mokun** [comment]
> these methods have not changed since 3.6.0 

Sorry I did change all of these methods in 3.6.2.

btw, I've just nailed down one of the issues that causes the slowness.

It has to do with the unknown phenomenon of spending a lot of time walking inside a rover. 

This causes excessive calling of the `Person::getMass()` method.

As soon as I remove calling `Person::getWalkSpeed` inside `WalkRoverInterior::walkingPhase`, some slowness go away.

**Comment by mokun** [comment]
@bevans2000 

It seems the slowness has nothing to do with pending tasks.

Visualvm shows the cpu is mostly used by performing tasks right now but can't reveal or pinpoint exactly how or why the first negative sleep occur on sol 1 between 750 and 850. 

So far, I can't determine the exact reason as to why it happens.

After the last commit, I almost reverted calling `addPendingTask` back to `assignTask`

The only 2 cases where a pending task is added  are :
1. Request medical assistance
2. Meet people

They have nothing to do with EVA tasks.

Can you take a look as to why the slowness still happens after 750 millisols on sol 1 ?

**Comment by mokun** [comment]
I just commented out the all codes in `Task.startNewTask()`  (except calling super..startNewTask() at the end). 

The slowness is still there at around 700 millisols on sol 1.

```java
	/**
	 * Starts a new Task by first checking for pending tasks.
	 */
	@Override
	public void startNewTask() {
		// Check if there are any assigned tasks that are pending
//		if (!getPendingTasks().isEmpty()) {
//			TaskJob pending = getPendingTask();
//			if (pending != null) {
//				Task newTask = pending.createTask(person);
//				
//				boolean isEVATask = newTask instanceof EVAOperation;
//				
//				if (newTask == null) {
//					// Note: need to track how some TaskJob has been done and no longer available.
//					logger.info(person, "'" + pending.getDescription() + "' was no longer needed and should be removed.");
//					
//					removePendingTask(pending);
//					
//					// Next, go to super.startNewTask() to find a new task
//				}
//
//				else if (person.isOutside()) {
//					
//					if (newTask.getName().toLowerCase().contains(SLEEP) || isEVATask) {
//						// Note :the person should 
//						// come in and rest and is no longer eligible for performing
//						// another EVA task
////						logger.info(person, "Outside already doing a EVA task. Not eligible for performing " + newTask.getName() + ".");
//						
//						// Skip doing anything for now
//					}
//
//					// Next, go to super.startNewTask() to find a new task
//				}
//				
//				else if (person.getMission() != null) {
////					logger.info(person, "On a mission. Not eligible for performing " + newTask.getName() + ".");
//					
//					// Skip doing anything for now
//					// Next, go to super.startNewTask() to find a new task
//				}
//				
//				else if (newTask != null && currentTask != null 
//					&& !newTask.getName().equals(getTaskName())
//					&& !newTask.getDescription().equals(currentTask.getDescription())
//					&& !isFilteredTask(currentTask.getDescription())) {
//					
//					// Note: this is the only eligible condition for replacing the
//					// current task with the new task
//					replaceTask(newTask);
//					// Remove the new task from the pending task list
//					removePendingTask(pending);
//					
//					// At this point, do NOT need to call super.startNewTask()
//					// or else the newTask will be replaced
//					return;
//				}
//			}
//		}

		super.startNewTask();	
		// Note that in super.startNewTask() in TaskManager, 
		// it will run replaceTask(selectedTask)
	}
```

**Comment by mokun** [comment]
Are there any ways to rework those regressive calls and break down what's inside `Task.performTask` and `Task.executeMappedPhase` ? 

They use 91.7% of CPU resources.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/aecb537d-5eb5-42e6-8d7b-73549dcb5035)

**Comment by bevans2000** [comment]
I can have a look tomorrow as I'm free in the evening g

**Comment by bevans2000** [comment]
My guess is there is a Task that can't co plate the execute phase and it just spins around until the time slice is consumed. We had a similiar problem a long time ago which we fixed so I'm confident we can solve it.

**Comment by mokun** [comment]
> My guess is there is a Task that can't co plate the execute phase and it just spins around until the time slice is consumed.

oic. It sounds like a walking task. 

It dawns on me that I'll create one-person settlement to test this theory.

**Comment by mokun** [comment]
@bevans2000 

Are you able to find anything yet ?

**Comment by mokun** [comment]
I wonder if it has to do with reentrant lock in Weather class !?

See these two commits https://github.com/mars-sim/mars-sim/commit/c2e31cd2b4c2b6e8016d89a318c565dadd4b8e95 and https://github.com/mars-sim/mars-sim/commit/5469ce2d0d5f81cc194301fa9bfc0d7954bd6842.

**Comment by mokun** [comment]
> I wonder if it has to do with reentrant lock in Weather class !?

After I commented out the .lock() and .unlock(), the negative sleep still happens at around 700 millisol on sol 1 (if I set the time ratio to 2048x since the beginning).

**Comment by bevans2000** [comment]
I doubt it concerns the lock. I've not had time this week yet as  even busy at work. Are you investigating ut on the master or 3.6 branch?

**Comment by mokun** [comment]
> Are you investigating ut on the master or 3.6 branch?

I'm making changes on 3.6.X branch.

**Comment by bevans2000** [comment]
I don't know the cause but I have found the reason for the slowdown. I've made a temp change in TaskManager and there are Walk tasks inside a Rover that are consuming a lot of iterations in ```Task.executeMappedPhase``` because each call to the Walk task is not consume all the available time.
So in this one pulse below there are over 17 million calls to Walk.performMappedPhase method. 
@mokun Something must be different in the Walk phase inside a Rover?

```
01-Adir-02:682.548 (Warning) Task [x6] : [0.0000 N 0.0000 W - Desert Fox] Rik Declercq - Walking inside a rover took excessive iteration to advance; cycles=1390828
01-Adir-02:682.548 (Warning) Task [x7] : [0.0000 N 0.0000 W - Desert Fox] Rik Declercq - Walking inside a rover took excessive iteration to advance; cycles=1341334
01-Adir-02:682.548 (Info) ExitAirlock : [Schiaparelli Point - EVA Airlock 3] Francesco Bianchi - Airlock is not in egress mode. Current task: 
Proposing a Astronomy Study.
01-Adir-02:682.548 (Info) TendGreenhouse [x27] : [Schiaparelli Point - Large Greenhouse 1] LukßÜ N?mec - Tending Tomato.
01-Adir-02:682.548 (Warning) Task [x3] : [0.0000 N 0.0000 W - Desert Fox] Nakshatra Chandra - Walking inside a rover took excessive iteration to advance; cycles=3786564
01-Adir-02:682.548 (Warning) Task [x3] : [0.0000 N 0.0000 W - Desert Fox] Nakshatra Chandra - Walking inside a rover took excessive iteration to advance; cycles=3859496
01-Adir-02:682.548 (Warning) Task [x3] : [0.0000 N 0.0000 W - Desert Fox] Nakshatra Chandra - Walking inside a rover took excessive iteration to advance; cycles=3363661
01-Adir-02:682.548 (Warning) Task [x3] : [0.0000 N 0.0000 W - Desert Fox] Nakshatra Chandra - Walking inside a rover took excessive iteration to advance; cycles=3366437
01-Adir-02:682.548 (Warning) LivingAccommodations : [Schiaparelli Point] Lander Hab 1 -  All beds have been taken (# Registered Beds: 4, Bed Capacity: 4).
01-Adir-02:682.548 (Warning) Task [x5] : [0.0000 N 0.0000 W - Desert Fox] Maria Kask - Walking inside a rover took excessive iteration to advance; cycles=1178693
01-Adir-02:682.548 (Warning) Task [x7] : [0.0000 N 0.0000 W - Desert Fox] Maria Kask - Walking inside a rover took excessive iteration to advance; cycles=1236509
```

**Comment by mokun** [comment]
> Walk tasks inside a Rover that are consuming a lot of iterations

That's a very good news you nailed that down to exactly where.

I suppose we're not talking about it's not a person inside a rover that's inside a garage, right ?

It's a person inside a vehicle that's parked in the vicinity of a settlement on Mars surface, right ?

**Comment by bevans2000** [comment]
> > Walk tasks inside a Rover that are consuming a lot of iterations
> 
> That's a very good news you nailed that down to exactly where.
> 
> I suppose we're not talking about it's not a person inside a rover that's inside a garage, right ?
> 
> It's a person inside a vehicle that's parked in the vicinity of a settlement on Mars 
Could be when the vehicle is still in the surface I guess but definitely at a Settlement. 
The logic is based on the premise that any Task.performMappedPhase implementation should aim to use all the time available or end the Task. These Walk tasks are not following the rules. 
I'll leave you to look at the Walk problem? 
I can make the Task code more defensive so this condition is flagged sooner. It theory there no need for the loop because the Mind class has a better failsafe logic so I'll look at whether this lower check is needed.

**Comment by mokun** [comment]
Okay, for the time being, I'll simply make walkingPhase() in `WalkRoverInterior` return 0 to get rid of the problem.

**Comment by bevans2000** [comment]
Has making it return zero fixed the problem?

**Comment by mokun** [comment]
> Has making it return zero fixed the problem?

Yes. It does.

However, mission vehicles currently can't depart from a settlement.

This should be a separate issue.

**Comment by mokun** [comment]
> However, mission vehicles currently can't depart from a settlement.

It will say rover en route to a site but it picks up no speed. 

A person is driving the rover.

I look at AbstractVehicleMission where I restored calling LoadVehicleMeta's createLoadJob(), instead of using assignTask().

Also in RoverMission, where it uses either createUnloadJob() or assignTask().

Everything looks normal.
