### ISSUE TITLE
mars-sim-headless/target/ now needs a pom.xml, exec-maven-plugin

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#175]
I just updated to git head and got an error https://paste.debian.net/1059000/

**Comment by mokun** [comment]
> [ERROR] The goal you specified requires a project to execute but there is
> no POM in this directory
> (/home/shirish/games/mars-sim/mars-sim-headless/target). Please verify you
> invoked Maven from the correct directory. -> [Help 1]
> org.apache.maven.lifecycle.MissingProjectException: The goal you specified
> requires a project to execute but there is no POM in this directory
> (/home/shirish/games/mars-sim/mars-sim-headless/target). Please verify you
> invoked Maven from the correct directory.
> 

I have no idea as to why maven would suggest that at all. 

The thing is that mars-sim-headless/target/ simply holds compiled content from mars-sim-headless/src/

Therefore, mars-sim-headless/target/ should be empty until someone runs maven compile. 

See [directory structure](https://github.com/mars-sim/mars-sim/tree/master/mars-sim-headless)

**Comment by shirishag75** [comment]
but even that ends in a failure, see https://paste.debian.net/1059106/

**Comment by Urwumpe** [comment]
Use a different working directory for starting maven: 

~/games/mars-sim/mars-sim-headless

You had started it in src.

**Comment by shirishag75** [comment]
I used your suggestion and still got https://paste.debian.net/1059494/ :(

**Comment by Urwumpe** [comment]
Never had such issues using IntelliJ... did you compile the core already?

**Comment by mokun** [comment]
@shirishag75 , 

I've just added a new maven plug-in called *exec-maven-plugin* in mars-sim-headless. 

```
			<plugin>
		        <groupId>org.codehaus.mojo</groupId>
		        <artifactId>exec-maven-plugin</artifactId>
		        <version>1.6.0</version>
		        <executions>
		            <execution>
		                <goals>
		                    <goal>java</goal>
		                </goals>
		            </execution>
		        </executions>
		        <configuration>
		            <mainClass>org.mars_sim.headless.MarsProjectHeadlessStarter</mainClass>
		        </configuration>
		    </plugin>	
```	

Can you try running `mvn exec:java` in mars-sim-headless directory ?

**Comment by mokun** [comment]
Based the discussion [here](https://stackoverflow.com/questions/15013651/using-maven-execexec-with-arguments), I just fixed what should be the arguments. 

It should be as follows : 

```
			<plugin>
		        <groupId>org.codehaus.mojo</groupId>
		        <artifactId>exec-maven-plugin</artifactId>
		        <version>1.6.0</version>
		        <executions>
		            <execution>
		                <goals>
		                    <goal>java</goal>
		                </goals>
		            </execution>
		        </executions>
		        <configuration>
		            <executable>java</executable>
		            <!--mainClass>org.mars_sim.headless.MarsProjectHeadless</mainClass-->
		            <arguments>
               			<argument>-Djava.util.logging.config.file=logging.properties -cp .;*;jars\*</argument>
               			<argument>-classpath</argument>
            			<classpath/>
            			<argument>org.mars_sim.headless.MarsProjectHeadless</argument>           			
               			<argument>-Xms256m -Xmx1024m -new</argument>
              		</arguments>
		        </configuration>
		    </plugin>	
```
Run `mvn exec:exec` in mars-sim-headless directory and it will instantly compile and run mars-sim without having to go through those maven test cases.

**Comment by shirishag75** [comment]
I tried both but came up empty :(

:~/games/mars-sim/mars-sim-headless$ git log --oneline
5f5c21a11 (HEAD -> master, origin/master, origin/HEAD) Attempting to fix malfunction repair issue

this is to share I am on the latest head. 

I tried both the options and both resulted in a build-failure - 

See https://paste.debian.net/1059755/

**Comment by shirishag75** [comment]
In both the keyword statement seems to be this - 

`Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 in http://jcenter.bintray.com/ was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced

`

**Comment by Urwumpe** [comment]
Yes, but the key problem is: It is not in your local repository. And it does not refer to the pom.xml in the parent directory. But the parent block also exists referring to the top level project.

Did you already try a "maven clean install" on the submodule?

**Comment by mokun** [comment]
Since the openjfx 11 package doesn't work yet in the command line maven, can you make sure that in mars-sim's pom.xml, the mars-sim-ui is being commented out everytime you run maven ?

**Comment by shirishag75** [comment]
> Yes, but the key problem is: It is not in your local repository. And it does not refer to the pom.xml in the parent directory. But the parent block also exists referring to the top level project.
> 
> Did you already try a "maven clean install" on the submodule?

which submodule ? mars-sim-headless or some other module ?

**Comment by shirishag75** [comment]
@mokun btw there seems to be some sort of issue in the parent pom.xml , I think only one of the two are correct, see line 151 and line 152 - 

```
<!-- <module>mars-sim-network</module-->
<!-- module>mars-sim-service</module-->
```

This is how modules look at my end now - 

```
$ cat pom.xml | grep module
	<modules>
		<!--module>mars-sim-android</module -->
		<module>mars-sim-core</module>
		<module>mars-sim-headless</module>
		<module>mars-sim-main</module>
		<module>mars-sim-mapdata</module>
		<!-- module>mars-sim-network</module-->
		<!-- module>mars-sim-service</module-->
		<!-- module>mars-sim-ui</module-->
	</modules>
```

**Comment by mokun** [comment]
It's just xml formatting :

**Comment by mokun** [comment]
> Did you already try a "maven clean install" on the submodule?

As of this moment, some maven tests fail to run. That's because recently, I got rid of the instances in a lot of classes such as Building, BuildingManager, Person, Robot, Settlement, etc. and replaced them with calling some lookup maps in UnitManager.

I'll need to fix the test cases first.

To me, I encounter no issues running `mvn exec:exec` in Eclipse under Java 10.

**Comment by shirishag75** [comment]
> It's just xml formatting :
> 
> ```
> 
> ```
> 
> To compile/run the headless version, we only need the following 4 modules :
> 
> ```
> 		<module>mars-sim-core</module>
> 		<module>mars-sim-headless</module>
> 		<module>mars-sim-main</module>
> 		<module>mars-sim-mapdata</module>
> ```
> 
> To compile/run the JavaFx version, we'll need the above 4 plus the one below :
> 
> ```
> 		<module>mars-sim-ui</module>
> ```

I know that,  it's just sometimes I forget to turn it off,  especially when I have to git pull and the pom.xml which I have modified needs to be removed or stashed (which happens every now and then.) In that process I sometimes don't remember to do the same.

**Comment by shirishag75** [comment]
I updated to the latest build (r4758) and still get the same build failure  -

https://paste.debian.net/1060004/

You can see the start of the build failure at line 205 itself - 

```
[DEBUG] =======================================================================
[WARNING] The POM for net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 is missing, no dependency information available
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=435528, ConflictMarker.markTime=87999, ConflictMarker.nodeCount=3, ConflictIdSorter.graphTime=239456, ConflictIdSorter.topsortTime=178791, ConflictIdSorter.conflictIdCount=2, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2113173, ConflictResolver.conflictItemCount=2, DefaultDependencyCollector.collectTime=11982479, DefaultDependencyCollector.transformTime=4486439}
[DEBUG] net.sf.mars-sim:mars-sim-headless:jar:3.1.0-b2
[DEBUG]    junit:junit:jar:4.12:test
[DEBUG]    net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2:compile
```

**Comment by mokun** [comment]
@shirishag75 , let's do the usual `mvn clean package install -DcompilerArgs` once. I've fixed the maven test. It should have no problem going through the test cases.

After that, run `mvn exec:exec` 

Note: make sure you don't do `mvn exec:java`. I need to do it differently and `exec:java` won't work in my eclipse/maven setup.

**Comment by shirishag75** [comment]
It still fails - 

```
~/games/mars-sim/mars-sim-headless$ mvn clean package install -DcompilerArgs 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< net.sf.mars-sim:mars-sim-headless >------------------
[INFO] Building mars-sim-headless 3.1.0-b2
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from jcenter: http://jcenter.bintray.com/net/sf/mars-sim/mars-sim-core/3.1.0-b2/mars-sim-core-3.1.0-b2.pom
Downloading from mars-sim: https://mars-sim.sourceforge.io/maven-repo/net/sf/mars-sim/mars-sim-core/3.1.0-b2/mars-sim-core-3.1.0-b2.pom
Downloading from central: https://repo.maven.apache.org/maven2/net/sf/mars-sim/mars-sim-core/3.1.0-b2/mars-sim-core-3.1.0-b2.pom
[WARNING] The POM for net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 is missing, no dependency information available
Downloading from jcenter: http://jcenter.bintray.com/net/sf/mars-sim/mars-sim-core/3.1.0-b2/mars-sim-core-3.1.0-b2.jar
Downloading from mars-sim: https://mars-sim.sourceforge.io/maven-repo/net/sf/mars-sim/mars-sim-core/3.1.0-b2/mars-sim-core-3.1.0-b2.jar
Downloading from central: https://repo.maven.apache.org/maven2/net/sf/mars-sim/mars-sim-core/3.1.0-b2/mars-sim-core-3.1.0-b2.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.818 s
[INFO] Finished at: 2019-01-14T03:39:49+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mars-sim-headless: Could not resolve dependencies for project net.sf.mars-sim:mars-sim-headless:jar:3.1.0-b2: Could not find artifact net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 in jcenter (http://jcenter.bintray.com/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by shirishag75** [comment]
Using -x got the following story - 

`[ERROR] Failed to execute goal on project mars-sim-headless: Could not resolve dependencies for project net.sf.mars-sim:mars-sim-headless:jar:3.1.0-b2: Failure to find net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 in http://jcenter.bintray.com/ was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced -> [Help 1]
`

**Comment by shirishag75** [comment]
> @shirishag75 , let's do the usual `mvn clean package install -DcompilerArgs` once. I've fixed the maven test. It should have no problem going through the test cases.
[snipped]

I dunno which tests you fixed as there is no commit r4758 or maybe you forgot to push ?
