### ISSUE TITLE
Optimise UnitManager Unit

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#355]
**Describe the bug**
Each Unit is stored twice, once for the specific type and once for the general Unit. Also there are duplicate methods on the different Unit types.
The `getUnitById` method is heavily used and it could be optimised.

**Expected behavior**
The type of Unit should be embedded in the UnitIdentifier since this will allow the correct Unit Map to be identified very efficiently.
The generation on the next identifier can be consolidated into the Unit base class.

**Comment by bevans2000** [comment]
These changes can go further and move the equals & hashcode methods into the base class since the identifier will be guaranteed to be unique across ALL Units. 
MarsSurface is an problem because it is treated as a singleton but referenced in multiple ways, by fixed ID, by static reference and by instanceof. Probably for Planet Units; the identifiers should be fixed and reserved; maybe a handled by a PlanetUtil class to ringfence them. This would allow the UnitManager to become more independent and just manage generic Units.

**Comment by mokun** [comment]
> Probably for Planet Units; the identifiers should be fixed and reserved; maybe a handled by a PlanetUtil class to ringfence them

That'll be really nice for mars-sim to become [multi-planetary](https://www.liebertpub.com/doi/10.1089/space.2018.29013.emu) soon 😃

**Comment by bevans2000** [comment]
Going to widen the scope to remove anything non-Unit from the UnitManager to correctly let it have the responsibility of managing Units. 
The methods to support Commander & Unit Names will be relocated to a more appropriate location.

**Comment by bevans2000** [comment]
There is still some work to do with the Planet support.
I feel that the role of the `UnitManager` is a bit mixed at the moment. The logic concerning Unit names & Commander setting should be oved out so the UnitManager can be focussed on managing units.

**Comment by mokun** [comment]
> The logic concerning Unit names & Commander setting should be oved out so the UnitManager can be focussed on managing units.

Agreed. UnitManager has been responsible for too many things as we speak.

**Comment by bevans2000** [comment]
I think we need a `SimulationBuilder` that is a transient class used just to bootstrap a new Simulation.

**Comment by bevans2000** [comment]
Last night did the first cut of removing the ReportingAuthority dependency from the UnitManager. However to do it well it will overlap with some the desires of #363, e.g. simplifying the enum items.

**Comment by bevans2000** [comment]
Running some long simulation runs to check these changes on a branch. I've had to expand it to some of the XML files to make sure they are using the code for the ReportingAuthority instead of the long name. This actually is better because the long name can change with a different language binding which would break some of the logic. The logic being based on the enum code is independent of the selected language.

**Comment by bevans2000** [comment]
Done the work now on introducing a `SettlementBuilder` that is responsible for creating a fully populated Settlement. This removes the logic from `UnitManager` and allows it to be reused in the ArrivingSettlement task as well to provide a consistent approach. Logic is much cleaner and less coupled.
Uncovered some problems in the UI table with them failing if Units are added mid-simulation.
The CrewEditor & ArrivingSettlement reflect the selecting Sponsor now as well. But there a problem in how the Beta Crew is saved in the Crew Config, I can't see how it ever worked. Will revisit it later.
Running some long simulation tests now.

**Comment by mokun** [comment]
@bevans2000 

Can you check why it's affecting the input of coordinates of a settlement in the table in Site Editor (aka SimulationConfigEditor) ?

My input would get stuck and unable to come out of it.

**Comment by mokun** [comment]
I've just tried fixing it but it has nothing to do with the existing validation of lat and long. So when I commented out checkForAllErrors(), checkRepeatingLatLon(), checkLatLon() methods in setValueAt(), they still get stuck. 

The only way to get "unstuck" is to hit the remove button.

**Comment by mokun** [comment]
Now I know why it keeps getting error and red text printed out.

![image](https://user-images.githubusercontent.com/1168584/125570753-8ac78fd9-5c11-4bab-ad2f-df5639f136f3.png)

The degree symbol is not compatible with the validation.

If the player ever change the lat or lon, he won't be able to input the degree symbol anyway. 

So it's not needed.

Can we remove the symbol ?

**Comment by mokun** [comment]
Or we could insert the degree symbol on behalf of the player after a player is done with typing in a lat/lon and hit enter.

It's just a matter of changing out the following blocks of code in the setValueAt(). 

Note that I commented them out in the last commit because they are incompatible with the degree symbol.

```
					case LAT_COL:
//						String latStr = ((String) aValue).trim();
//						double doubleLat = 0;
//						String dir1 = latStr.substring(latStr.length() - 1, latStr.length());
//						dir1.toUpperCase();
//						if (dir1.toUpperCase().equals("N") | dir1.toUpperCase().equals("S")) {
//							if (latStr.length() > 2) {
//								doubleLat = Double.parseDouble(latStr.substring(0, latStr.length() - 1));
//								doubleLat = Math.round(doubleLat * 100.0) / 100.0;
//								info.latitude = doubleLat + " " + dir1;
//							} else
//								info.latitude = (String) aValue;
//						} else
							info.latitude = (String) aValue;

						checkLat(info.latitude);
						checkRepeatingLatLon();
						
						break;

					case LON_COL:
//						String longStr = ((String) aValue).trim();
//						double doubleLong = 0;
//						String dir = longStr.substring(longStr.length() - 1, longStr.length());
//						dir.toUpperCase();
//						if (dir.toUpperCase().equals("E") | dir.toUpperCase().equals("W")) {
//							if (longStr.length() > 2) {
//								doubleLong = Double.parseDouble(longStr.substring(0, longStr.length() - 1));
//								doubleLong = Math.round(doubleLong * 100.0) / 100.0;
//								info.longitude = doubleLong + " " + dir;
//							} else
//								info.longitude = (String) aValue;
//						} else
							info.longitude = (String) aValue;

						checkLon(info.longitude);
						checkRepeatingLatLon();
						
						break;
					} 
```

**Comment by bevans2000** [comment]
No let's just drop the degree symbol. Long/Lat format is clear without the degree symbol. Plus if it is not expected to be enter by a user then it should not be displayed. Creating the degree sy bol is not easy kn all keyboards. I will sort it out later

**Comment by mokun** [comment]
Now that the degree symbol is gone, I'll add back the initial input validation block for lat and lon to setValueAt(). 

It will change the direction to an upper case character and add a whitespace between the number and the direction.

It will truncate the number to 2 decimal places since we compare coordinates up to 2 decimal places only. 

In future when we resolve the map in high resolution, we can change it to 3 or 4 decimal places.

**Comment by mokun** [comment]
@bevans2000 ,

While preparing for a delivery mission, it's attempting to look for some type of equipment but the unit is not found. 

I wonder why.

```
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130292 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130388 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130420 type:EQUIPMENT
00-Adir-05:305.075 (Info) DeliveryUtil : [Zvezda] Drone 011 - yeast (balue: 178.9)  Buyer: Zvezda  Seller: Tian Cheng.
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
00-Adir-05:305.075 (Warning) UnitManager : Unit not found 130468 type:EQUIPMENT
```

**Comment by bevans2000** [comment]
I noticed the same thing on a Delivery mission last night. It's very odd. Does a delivery mission create or remove any equipment?

**Comment by mokun** [comment]
> I noticed the same thing on a Delivery mission last night. It's very odd. Does a delivery mission create or remove any equipment?

I imagine a delivery mission may sell containers such as bags (equipment) or need a gas canister to hold certain amount of gas to be sold.

**Comment by mokun** [comment]
See this example of using bag to hold sugar to be delivered and sold

![image](https://user-images.githubusercontent.com/1168584/127445920-f59c3f1f-c203-43d1-879e-dc653e789517.png)

**Comment by bevans2000** [comment]
Does it remove Equipment once it is completed? That could cause a problem I think.

**Comment by mokun** [comment]
> Does it remove Equipment once it is completed? That could cause a problem I think.

Yes it should load/transfer the bag from the settlement to the Drone.

**Comment by bevans2000** [comment]
I meant does the Mission create any extra Equipment for the mission.? I think this can only happen for 2 reasons

1. Equipment is constructed without registering it with the Unit Manager. All Equipment should be created via the factory which registers it.
2. An Equipment is removed from  the UnitManager but it continues to be used.
As this only started happening recently for a very specific case it must be something in the new Delivery code. Both of the above can be investigate from static code analysis of the call hierarchy.

**Comment by mokun** [comment]
It may create some hypothetical equipment in Delivery Meta just to compute a profit score to see if this mission is a good idea or not

**Comment by mokun** [comment]
I also commented out one or two of those *throw new IllegalStateException()* statements in retrieveUnit() and elsewhere in Inventory: 

`throw new IllegalStateException("Unit: " + unit + " could not be stored in/on " + getOwner().getName()); `

**Comment by bevans2000** [comment]
I have found a bug in the `LoadVehicleGarageTask` where it continuously creates new Equipment; I'm talking 1000s over the course of a long simulation run. Doesn't really explain the issue but it could be a factor.
I've slightly changing how Equipment are created so I can track them being created in a file as a temporary measure.
